#!/bin/sh

set +o noclobber # Why yes, I did mean to clobber that file.

hook()
{
  local _hook
  _hook="$1"

  (( _hooks_flag )) || return 0

  # System
  if paths exist "${shared_path}/deploy"
  then
    if paths exist "${shared_path}/deploy" &&
      files are executable "${shared_path}/deploy/$_hook"
    then
      log step "${_hook} ( ${shared_path##${project_path}/}/deploy/ )"
      hook_source "${shared_path}/deploy/$_hook" &> >(tee -a "${deploy_log_path}/${_hook}.log")

      log step success
    fi
  fi

  # System, Environment specific
  if [[ -n "${environment:-}" ]] &&
    files are executable "$shared_path/deploy/${environment}/${_hook}"
  then
    log step "${_hook} ( ${shared_path##${project_path}/}/deploy/${environment}/ )"
    hook_source "$shared_path/deploy/${environment}/${_hook}" &> >(tee -a "${deploy_log_path}/${_hook}.log")
    log step success
  fi

  # Project
  if paths exist "$shared_path/$project" &&
    files are executable "$shared_path/$project/config/deploy/${_hook}"
  then
    log step "${_hook} ( ${shared_path##${project_path}/}/${project}/config/deploy/ )"
    hook_source "$shared_path/$project/config/deploy/${_hook}" &> >(tee -a "${deploy_log_path}/${_hook}.log")
    log step success
  fi

  # Project, environment
  if [[ -n "${environment}" ]] &&
    files are executable "$shared_path/$project/config/deploy/$environment/${_hook}"
  then
    log step "${_hook} ( ${shared_path##${project_path}/}/${project}/config/deploy/${environment}/ )"
    hook_source "$shared_path/$project/config/deploy/$environment/${_hook}" &> >(tee -a "${deploy_log_path}/${_hook}.log")
    log step success
  fi
}

hook_source()
{
  ( files source "$1" )
}

before_step()
{
  hook "before_$1" "$@"
}

after_step()
{
  hook "after_$1" "$@"
}

update()
{
  update_repository && release
}

update_repository()
{
  log step "update_repository ( ${shared_path##${project_path}/}/${project} )"
  fetch_uri "$repository_url" "$shared_path/$project" "${branch:-}"
  log step success

  paths enter "${shared_path}/${project}"

  log " TODO: **** move revision handling to fetch_uri ****"

  case "${scm_type}" in
    (git|github)
      if files exists ".gitmodules"
      then
        log step "Updating submodules"
        git submodule init > ${deploy_log_path}/git-submodules.log 2>&1
        git submodule update > ${deploy_log_path}/git-submodules.log 2>&1
        log step success
      fi

      if [[ -n "$revision" ]]
      then
        log step "Checking out revision '$revision'."
        git checkout $revision > ${deploy_log_path}/git-checkout.log 2>&1
        log step success
      else
        revision=$( git log --no-color -1 | awk '/commit/{print $2}')
        revision=${revision:0:7}
      fi

      if [[ -z "${branch}" ]]
      then
        branch=$( git branch --no-color | awk '/^\* /{print $2}')
      fi
      ;;
    (hg)
      if [[ -n "$revision" ]]
      then
        # TODO: Find out if this is how it's done for hg ;)
        log step "Checking out revision '$revision'."
        hg update $branch $revision  > ${deploy_log_path}/hg-update.log 2>&1
        log step success
      else
        log step "Updating branch '$branch'."
        hg update $branch > ${deploy_log_path}/hg-update.log 2>&1
        log step success
      fi
      ;;
    (svn)
      (( revision > 0 )) || return 0
      log step "Checking out revision $revision"
      svn checkout -r $revision > ${deploy_log_path}/svn-checkout.log 2>&1
      log step success
      ;;
  esac
}

stage()
{
  log step "stage ~ staging ${project} ${branch:-} ${revision:-} ( ${stage_path##${project_path}/} )" \
    rsync -ag --exclude=".${scm_type}/" "${shared_path}/${project}/" "${stage_path}"

  paths enter "$stage_path"

  paths create "$stage_path/public"
}

fail_stage()
{
  if paths exist "${stage_path}"
  then
    log step "stage fail ~ Removing stage release ( $stage_path )" \
      paths remove "${stage_path}"
  fi
}

release()
{
  typeset _prefix
  _prefix="${shared_path%/*}"

  #TODO: version detection failed !!!

  versionedfs add \
    path "${project_path}" \
    name "${project}" \
    version ${version:=$(date +"%Y-%m-%dT%H:%M:%S")} \
    source "$stage_path"

  versionedfs activate \
    path "${project_path}" \
    name "${project}" \
    version ${version:=$(date +"%Y-%m-%dT%H:%M:%S")}

  paths remove "$stage_path"

  paths enter "$release_path"
}

fail_release()
{
  if paths exist "$stage_path"
  then
    log step "discard ~ Discarding stage ( $discard_path/$timestamp )"
    paths move \
      from "$stage_path" \
      to "$discard_path/$timestamp"
    log step success
  fi

  if variables are nonempty "${initial_release}"
  then
    paths exist "$initial_release" || return 0
  else
    return 0
  fi

  paths create "$discard_path" "$deploy_log_path"

  # TODO: versionedfs last # switch to last version
  log step "Reverting to previous release $previous"
  paths move from "$previous" to "${release_path%/}"
  log step success
}

configure()
{
  local _name _file _path _paths _prefix _shared_public_path

  _prefix="${shared_path%/*}"
  _shared_public_path="${shared_path}/public"

  paths exist "${shared_path}/config" || return 0

  paths enter "${shared_path}/config"

  for _file in "${shared_path}"/config/*
  do
    _name="${_file##*/}"

    log step "  link ~ ${_name} ( ${shared_path##${project_path}/}/config/${_name} => $stage_path/config/${_name} )"

    paths remove "$stage_path/config/${_name}"
    files link symbolic \
      from "$shared_path/config/${_name}" \
      to "$stage_path/config/${_name}"

    log step success
  done

  if paths exist "$shared_path/db"
  then
    log step "  link ~ db path ( ${shared_path##${project_path}/}/db => ${stage_path##${project_path}/}/db )"
    paths remove "$stage_path/db"
    files link symbolic \
      from "$shared_path/db" \
      to "$stage_path/db"
    log step success
  fi

  for _path in tmp log pids #files
  do
    if paths exist "${stage_path}/${_path}"
    then
      paths remove "${stage_path}/${_path}"
    fi
    log step "  link ~ ${_path} ( ${shared_path##${project_path}/}/${_path} => ${stage_path##${project_path}/}/${_path} )"

    paths remove "${stage_path}/${_path}"
    files link symbolic \
      from "${shared_path}/${_path}" \
      to "${stage_path}/${_path}"
    log step success
  done

  paths exist "$shared_path/public/" ||
    error "\nPlease run the folloing command first and then retry:\n\tsm rails setup"

  _paths=($( find "${shared_path}/public" -mindepth 1 -maxdepth 1 -type d ))

  for _path in "${_paths[@]}"
  do
    _path="${_path#${_shared_public_path}/}"

    log step "  link ~ public ${_path} ( ${shared_path##${project_path}/}/public/${_path} => ${stage_path##${project_path}/}/public/${_path} )"

    paths remove "${stage_path}/public/${_path}"
    files link symbolic \
      from "${_shared_public_path}/${_path}" \
      to "${stage_path}/public/${_path}"

    log step success
  done
}

remove_releases()
{
  typeset _release
  while (( $# > 0 ))
  do
    _release="${1}"
    shift
    log "Removing old release ${_release}"
    paths remove "${_release}"
  done
}

record()
{ # TODO: What else could we record that would be useful?
  paths exist "${release_path}" || return 0 # Release failed, nothing to do...

  if [[ -n "${revision:-}" ]]
  then
    files write string "${revision}" to "${release_path}/revision"
  fi

  if [[ -n "${branch:-}" ]]
  then
    files write string "${branch}" to "${release_path}/branch"
  fi

  if [[ -n "${repository_url}" ]] # TODO: get this from the .uri file.
  then
    files write string "$repository_url" to "${release_path}/repository_url"
  fi

  if [[ -n "${timestamp:-}" ]]
  then
    files write string "${timestamp}" to "${release_path}/timestamp"
  fi
}

cleanup()
{
  paths exist "$project_path/previous" || return 0 # No old releases
  array is nonempty old_releases       || return 0 # No old releases

  paths enter "${project_path}/previous"
  remove_releases "${old_releases[@]}" ||
    log "There was an error removing old releases."
}

do_deploy()
{
  trace_filter "deploy" || set -o xtrace

  # Logging (http://nakedape.cc/wiki/ShellHacks 1.6.1, 1.7, 1.11)
  export log_file="${deploy_log_path}/deploy.log"
  touch "${log_file}"
  #exec 3>>"${log_file}"
  exec > >(tee -a "${log_file}") 2>&1
  # Error handling
  trap revert_on_error ERR
  trap revert_on_error ZERR

  # This will run any deploy hooks that are called
  #   (by hook file name)
  # Hooks are sourced into a subshell IF they are executable.
  # This means that users may disable hooks by changing their
  # execute bit.
  #
  if ! command exists rsync
  then
    error "The 'rsync' command was not found, please install rsync before using deploy."\
      "(Note that there is an rsync extension in the networking extension set)\n"\
      "root# sm sets install networking ; sm rsync package install"
  fi

  if paths exist "${release_path}"
  then # If release path already exists, start inside it.
    paths enter "$release_path"
  fi

  log "  Deploy started at ${timestamp}"
  step deploy
  log "  Deploy completed at $(date +%m.%d.%YT%H:%M:%S)"
}

deploy()
{
  typeset _step
  for _step in "${deploy_steps[@]}"
  do
    step "${_step}" &> >(tee -a "${log_file}")
  done
}

revert_on_error()
{
  result=$?
  trap "backtrace \"An errorr occured while reverting.\"" ERR
  trap "backtrace \"An errorr occured while reverting.\"" ZERR
  backtrace "A command has returned an not handled error code (${result})." no_exit 2>"${log_file}"
  log "\nAn error occured, reverting...\n  for details check deploy.$timestamp.log\n" >&2
  retreat >&2
  kill -s USR2 $APP_PID #to exit application not current subshell
}

revert()
{
  retreat
}

do_revert()
{
  log "  Reverting ..."
  retreat "deploy" "${deploy_steps[@]}"
}
