#!/bin/sh

hook()
{
  local _hook="$1"

  (( _hooks_flag )) || return 0

  # System
  if paths exist "${shared_path}/deploy"
  then
    if paths exist "${shared_path}/deploy" &&
      files are executable "${shared_path}/deploy/$_hook"
    then
      log_step "${_hook} ( ${shared_path##${project_path}/}/deploy/ )"
      hook_source "${shared_path}/deploy/$_hook" >> "${deploy_log_path}/${_hook}" 2>&1
      log_step success
    fi
  fi

  # System, Environment specific
  if [[ -n "${environment}" ]] &&
    files are executable "$shared_path/deploy/#{$environment}/${_hook}"
  then
    log_step "${_hook} ( ${shared_path##${project_path}/}/deploy/${environment}/ )"
    hook_source "$shared_path/deploy/#{$environment}/${_hook}" >> "${deploy_log_path}/${_hook}" 2>&1
    log_step success
  fi

  # Project
  if paths exist "$shared_path/$project" &&
    files are executable "$shared_path/$project/config/deploy/${_hook}"
  then
    log_step "${_hook} ( ${shared_path##${project_path}/}/${project}/config/deploy/ )"
    hook_source "$shared_path/$project/config/deploy/${_hook}" >> "${deploy_log_path}/${_hook}" 2>&1
    log_step success
  fi

  # Project, environment
  if [[ -n "${environment}" ]] &&
    files are executable "$shared_path/$project/config/deploy/$environment/${_hook}"
  then
    log_step "${_hook} ( ${shared_path##${project_path}/}/${project}/config/deploy/${environment}/ )"
    hook_source "$shared_path/$project/config/deploy/$environment/${_hook}" >> "${deploy_log_path}/${_hook}" 2>&1
    log_step success
  fi
}

hook_source()
{
  local _file="$1"
  ( files source "${_file}" )
}

before_step()
{
  local _name="$1"
  shift
  hook "before_${_name}" "$@"
}

after_step()
{
  local _name="$1"
  shift
  hook "after_${_name}" "$@"
}

update()
{
  update_repository && release
}

update_repository()
{
  log_step "update_repository ( ${shared_path##${project_path}/}/${project} )"
  fetch_uri "$repository_url" "$shared_path/$project" "${branch:-}"
  log_step success

  paths enter "${shared_path}/${project}"

  log_todo "  **** move revision handling to fetch_uri ****"

  case "${scm_type}" in
    git|github)
      if files exists ".gitmodules"
      then
        log_step "Updating submodules" \
        git submodule init 2>/dev/null && git submodule update
      fi

      if [[ -n "$revision" ]]
      then
        log_step "Checking out revision '$revision'." \
          git checkout $revision >/dev/null 2>&1
      else
        revision=$( git log --no-color -1 | awk '/commit/{print $2}')
        revision=${revision:0:7}
      fi

      [[ -n "${branch}" ]] ||
        branch=$( git branch --no-color | awk '/^\* /{print $2}')
      ;;

    hg)
      if [[ -n "$revision" ]]
      then
        # TODO: Find out if this is how it's done for hg ;)
        log_step "Checking out revision '$revision'." \
          hg update $branch $revision
      else
        log_step "Updating branch '$branch'." \
          hg update $branch
      fi
      ;;

    svn)
      (( revision > 0 )) || return 0

      log_step "Checking out revision $revision" \
        svn checkout -r $revision
      ;;
  esac

}

stage()
{
  log_step "stage ~ staging ${project} ${branch:-} ${revision:-} ( ${stage_path##${project_path}/} )" \
    rsync -ag --exclude=".${scm_type}/" "${shared_path}/${project}/" "${stage_path}"

  paths enter "$stage_path"

  paths create "$stage_path/public"
}

fail_stage()
{
  if paths exist "${stage_path}"
  then
    log_step "stage fail ~ Removing stage release ( $stage_path )" \
      paths remove "${stage_path}"
  fi
}

release()
{
  local _prefix="${shared_path%/*}"

  #TODO: version detection failed !!!

  versionedfs add \
    path "${project_path}" \
    name "${project}" \
    version ${version:=$(date +"%Y-%m-%dT%H:%M:%S")} \
    source "$stage_path"

  versionedfs activate \
    path "${project_path}" \
    name "${project}" \
    version ${version:=$(date +"%Y-%m-%dT%H:%M:%S")}

  paths remove "$stage_path"

  paths enter "$release_path"
}

fail_release()
{
  if paths exist "$stage_path"
  then
    log_step "discard ~ Discarding stage ( $discard_path/$timestamp )" \
      mv "$stage_path" "$discard_path/$timestamp"
  fi

  paths exist "$initial_release" || return 0

  paths create "$discard_path" "$deploy_log_path"

  # TODO: versionedfs last # switch to last version
  log_step "Rolling back to previous release $previous" \
    mv "$previous" "${release_path%/}"
}

configure()
{
  local _name _file _path _paths _prefix="${shared_path%/*}" \
    _shared_public_path="${shared_path}/public"


  paths exist "${shared_path}/config" || return 0

  paths enter "${shared_path}/config"

  for _file in "${shared_path}"/config/*
  do
    _name="${_file##*/}"

    log_step "  link ~ ${_name} ( ${shared_path##${project_path}/}/config/${_name} => $stage_path/config/${_name} )" \
      files link symbolic force from "$shared_path/config/${_name}" to "$stage_path/config/${_name}"
  done

  if paths exist "$shared_path/db"
  then
    log_step "  link ~ db path ( ${shared_path##${project_path}/}/db => ${stage_path##${project_path}/}/db )" \
      files link symbolic force from "$shared_path/db" to "$stage_path/db"
  fi

  for _path in tmp log pids #files
  do
    if paths exist "${stage_path}/${_path}"
    then
      paths remove "${stage_path}/${_path}"
    fi
    log_step "  link ~ ${_path} ( ${shared_path##${project_path}/}/${_path} => ${stage_path##${project_path}/}/${_path} )" \
      files link symbolic force from "${shared_path}/${_path}" to "${stage_path}/${_path}"
  done

  paths exist "$shared_path/public/" ||
    error "\nPlease run the folloing command first and then retry:\n\tsm rails setup"

  _paths=($( find "${shared_path}/public" -mindepth 1 -maxdepth 1 -type d ))

  for _path in "${_paths[@]}"
  do
    _path="${_path#${_shared_public_path}/}"

    log_step "  link ~ public ${_path} ( ${shared_path##${project_path}/}/public/${_path} => ${stage_path##${project_path}/}/public/${_path} )" \
      files link symbolic force from "${_shared_public_path}/${_path}" to "${stage_path}/public/${_path}"
  done
}

remove_releases()
{
  local _release
  while (( $# > 0 ))
  do
    _release="${1}"
    shift
    log "Removing old release ${_release}"
    paths remove "${_release}"
  done
}

record()
{ # TODO: What else could we record that would be useful?
  paths exist "${release_path}" || return 0 # Release failed, nothing to do...

  if [[ -n "${revision:-}" ]]
  then
    files write string "${revision}" to "${release_path}/revision"
  fi

  if [[ -n "${branch:-}" ]]
  then
    files write string "${branch}" to "${release_path}/branch"
  fi

  if [[ -n "${repository_url}" ]] # TODO: get this from the .uri file.
  then
    files write string "$repository_url" to "${release_path}/repository_url"
  fi

  if [[ -n "${timestamp:-}" ]]
  then
    files write string "${timestamp}" to "${release_path}/timestamp"
  fi
}

cleanup()
{
  paths exist "$project_path/previous" || return 0 # No old releases
  array is nonempty old_releases       || return 0 # No old releases

  paths enter "${project_path}/previous"
  remove_releases "${old_releases[@]}" ||
    log "There was an error removing old releases."
}

do_deploy()
{
  # Logging (http://nakedape.cc/wiki/ShellHacks 1.6.1, 1.7, 1.11)
  export log_file="${deploy_log_path}/deploy.log"
  exec 3>>"${log_file}"
  exec &> >(tee -a "${log_file}")
  # Error handling
  trap revert_on_error ERR

  # This will run any deploy hooks that are called
  #   (by hook file name)
  # Hooks are sourced into a subshell IF they are executable.
  # This means that users may disable hooks by changing their
  # execute bit.
  #
  if ! command exists rsync
  then
    error "The 'rsync' command was not found, please install rsync before using deploy."\
      "(Note that there is an rsync extension in the networking extension set)\n"\
      "root# sm sets install networking ; sm rsync package install"
  fi

  if paths exist "${release_path}"
  then # If release path already exists, start inside it.
    paths enter "$release_path"
  fi

  step deploy

  log "  Deploy started at ${timestamp} and completed at $(date +%m.%d.%YT%H:%M:%S)"
}

deploy()
{
  local _step
  for _step in "${deploy_steps[@]}"
  do
    #step "${deploy_steps[@]}" >> "${deploy_log_path}/${_hook}" 2>&1
    step "${_step}" 2>&3
    #step "${_step}" >> "${deploy_log_path}/${_step}" 2>&1
  done
}

revert_on_error()
{
  trap "backtrace \"An errorr occured while reverting.\"" ERR
  local status=$?
  backtrace "A command has returned an not handled error code (${status})." no_exit 2>&3
  log "\nAn error occured, reverting...\n  for details check deploy.$timestamp.log\n" >&2
  retreat >&2
  kill -s USR2 $APP_PID #to exit application not current subshell
}

revert()
{
  retreat
}

do_revert()
{
  log "  Reverting ..."
  retreat "deploy" "${deploy_steps[@]}"
}

