#!/usr/bin/env bash

if ! command_exists rsync
then
  error "rsync is required in order to use the deploy extension, "\
    "please install rsync before continuing\n"\
    "  bdsm rsync package install"
fi

if variable_is_empty repository_url
then
  error "The project's repository_url must be set in configuration files (eg: ~/.bdsmrc)"
fi

true \
  ${discard_path:="${shared_path}/discard"} \
  ${previous_path:="${project_path}/previous"} \
  ${stage_path:="${project_path}/stage"} \
  ${deploy_log_path:="${shared_path}/log/deploy"} \
  ${hooks_flag:=1}

ensure_paths_exist "$previous_path" "$discard_path" "$deploy_log_path"

previous_releases=$(
  find "${previous_path}/" -mindepth 1 -maxdepth 1 -type d | sort
)

previous="${previous_releases[0]}"

old_releases=($(
  find "${previous_path}/" -mindepth 1 -maxdepth 1 -type d | sort -r |
  awk "NR > ${keep_releases:-3} { print \$0 }"
))

timestamp="$(date +%m.%d.%YT%H:%M:%S)"

deploy_steps=(
  update_repository stage_current configure symlink
  replace_current cleanup record
)

