#!/usr/bin/env bash

description "Deployment management extension."

note "If any one of the deployment steps fail, then the deploy should fail as well.  If this is not the case please let me know right away and provide a gist of 'sm --trace deploy' so that I can inspect where the failure is occurring. "

resource "http://extensions.beginrescueend.com/deploy/ #(documentation)"
resource "https://www.pivotaltracker.com/projects/26822 #(development tracker)"

action "deploy" \
  "Deploy application from ${shared_path}"

action "rollback" \
  "Reset ~/current to the most recent previous release."

action "help" \
  "Display this help text."

description "
Deployment Steps:

1. update_repository

2. deploy:

  a. stage
  b. configure
  c. symlink
  d. replace_current
  e. cleanup
  f. record

Hooks

  For each step there are two hooks one that is run before ('before_' prefix)
    and one that is run after ('after_' prefix).

  Each hook is the name of a step listed above prefixed with either before_ or
  after_.  For example around steps a - f there is a 'before_deploy' and an
  'after_deploy'

  If you want to execute a task before the code is moved in place but after
    everything is setup in the staging area, use 'before_replace_current' hook.

Prerequisites

   - git
   - curl
   - rsync
   - subversion / mercurial (if the application's repository uses them).
"

show_help usage

